/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrms.forms;

import com.hrms.classes.DBClass;
import com.hrms.classes.ImageUtility;
import com.hrms.classes.StatusClass;
import com.hrms.classes.Utility;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class MainForm1 extends javax.swing.JFrame {
      SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
      Random rd=new Random();
      DBClass db=new DBClass();
    /**
     * Creates new form MainForm
     */
    public MainForm1() {
        initComponents();
        setTitle("Human Resourse Management System [UserName: "+StatusClass.user+"]");
        ImageUtility.changeFrameBackgroundImage(this, "src/images/hback.jpg");
        Timer t=new Timer(1000,e->{
            Date d=new Date();
            String s=sdf.format(d);
            lbl2.setText(s);
            
            //Update color
            int r=rd.nextInt(256);
            int g=rd.nextInt(256);
            int b=rd.nextInt(256);
            Color c=new Color(r, g, b);
            lbl1.setForeground(c);
            lbl2.setForeground(c);
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jSeparator20 = new javax.swing.JSeparator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnumaster = new javax.swing.JMenu();
        mnucompanyinfo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuemployee = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnusupplier = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnucompany = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnubank = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Emplist = new javax.swing.JMenuItem();
        jSeparator31 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator33 = new javax.swing.JPopupMenu.Separator();
        mnudept = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuapplicant = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuapplicanttest = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnuselectedapplicant = new javax.swing.JMenuItem();
        mnutestditalis = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuempattendence = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        mnuleaverequest = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        jMenu17 = new javax.swing.JMenu();
        mnusalary = new javax.swing.JMenuItem();
        jSeparator36 = new javax.swing.JPopupMenu.Separator();
        mnusalaryditails = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnucustreport = new javax.swing.JMenuItem();
        jSeparator29 = new javax.swing.JPopupMenu.Separator();
        mnusuppreport = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        mnuprodreport = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JPopupMenu.Separator();
        mnubankreport = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        mnuchangepassword = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        mnuapplication = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mnuuser = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        mnubackup = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();
        mnucal = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        mnunotepad = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        mnupaint = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenu15 = new javax.swing.JMenu();
        mnuword = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        mnuexcle = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        mnupowerpoint = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        mnuaccess = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jMenu16 = new javax.swing.JMenu();
        mnuchrome = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        mnufirebox = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        mnuexplore = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        mnulogout = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenuItem24.setText("jMenuItem24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Human Resource Management Systeam");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setText("Human Resourse Management System");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(30, 30, 30)
                .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        mnumaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/master.PNG"))); // NOI18N
        mnumaster.setText(" Master");

        mnucompanyinfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnucompanyinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile1.jpg"))); // NOI18N
        mnucompanyinfo.setText(" Imformation");
        mnucompanyinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucompanyinfoActionPerformed(evt);
            }
        });
        mnumaster.add(mnucompanyinfo);
        mnumaster.add(jSeparator1);

        mnuemployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee_32x32.png"))); // NOI18N
        mnuemployee.setText("Employee");
        mnuemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuemployeeActionPerformed(evt);
            }
        });
        mnumaster.add(mnuemployee);
        mnumaster.add(jSeparator2);

        mnusupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserGroup_32x32.png"))); // NOI18N
        mnusupplier.setText("Department");
        mnusupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusupplierActionPerformed(evt);
            }
        });
        mnumaster.add(mnusupplier);
        mnumaster.add(jSeparator3);

        mnucompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company2.png"))); // NOI18N
        mnucompany.setText("Company");
        mnucompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucompanyActionPerformed(evt);
            }
        });
        mnumaster.add(mnucompany);
        mnumaster.add(jSeparator4);

        mnubank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash.png"))); // NOI18N
        mnubank.setText("Bank");
        mnubank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubankActionPerformed(evt);
            }
        });
        mnumaster.add(mnubank);

        jMenuBar1.add(mnumaster);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee_32x32.png"))); // NOI18N
        jMenu1.setText("Employee");

        Emplist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee_32x32_1.png"))); // NOI18N
        Emplist.setText("Employee List");
        Emplist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmplistActionPerformed(evt);
            }
        });
        jMenu1.add(Emplist);
        jMenu1.add(jSeparator31);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserGroup_32x32.png"))); // NOI18N
        jMenuItem2.setText("New Employee Profile");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator32);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        jMenuItem3.setText("Issue Experience Letter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator33);

        mnudept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company2.png"))); // NOI18N
        mnudept.setText("Department");
        mnudept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnudeptActionPerformed(evt);
            }
        });
        jMenu1.add(mnudept);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ecommerce_Icons_Rose_Color-50-32.png"))); // NOI18N
        jMenu2.setText("Recruitmenet");

        mnuapplicant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        mnuapplicant.setText("Applicant");
        mnuapplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuapplicantActionPerformed(evt);
            }
        });
        jMenu2.add(mnuapplicant);
        jMenu2.add(jSeparator8);

        mnuapplicanttest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ordering.png"))); // NOI18N
        mnuapplicanttest.setText("Applicant Test");
        mnuapplicanttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuapplicanttestActionPerformed(evt);
            }
        });
        jMenu2.add(mnuapplicanttest);
        jMenu2.add(jSeparator9);

        mnuselectedapplicant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment-icon.png"))); // NOI18N
        mnuselectedapplicant.setText("Selected Applicant");
        mnuselectedapplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuselectedapplicantActionPerformed(evt);
            }
        });
        jMenu2.add(mnuselectedapplicant);

        mnutestditalis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment-icon.png"))); // NOI18N
        mnutestditalis.setText("Test Details");
        mnutestditalis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutestditalisActionPerformed(evt);
            }
        });
        jMenu2.add(mnutestditalis);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Time Management");

        mnuempattendence.setText("Employee Attendence");
        mnuempattendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuempattendenceActionPerformed(evt);
            }
        });
        jMenu5.add(mnuempattendence);
        jMenu5.add(jSeparator11);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Leave Management");

        mnuleaverequest.setText("Leave Request");
        mnuleaverequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuleaverequestActionPerformed(evt);
            }
        });
        jMenu6.add(mnuleaverequest);
        jMenu6.add(jSeparator35);

        jMenuBar1.add(jMenu6);

        jMenu17.setText("Payroll");

        mnusalary.setText("Salary");
        mnusalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusalaryActionPerformed(evt);
            }
        });
        jMenu17.add(mnusalary);
        jMenu17.add(jSeparator36);

        mnusalaryditails.setText("Salary Details");
        mnusalaryditails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusalaryditailsActionPerformed(evt);
            }
        });
        jMenu17.add(mnusalaryditails);

        jMenuBar1.add(jMenu17);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        jMenu8.setText("Reports");

        mnucustreport.setText(" Employee Report");
        mnucustreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucustreportActionPerformed(evt);
            }
        });
        jMenu8.add(mnucustreport);
        jMenu8.add(jSeparator29);

        mnusuppreport.setText("Supplier Report");
        mnusuppreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusuppreportActionPerformed(evt);
            }
        });
        jMenu8.add(mnusuppreport);
        jMenu8.add(jSeparator30);

        mnuprodreport.setText("Product Report");
        mnuprodreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuprodreportActionPerformed(evt);
            }
        });
        jMenu8.add(mnuprodreport);
        jMenu8.add(jSeparator34);

        mnubankreport.setText("Bank Report");
        mnubankreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubankreportActionPerformed(evt);
            }
        });
        jMenu8.add(mnubankreport);

        jMenuBar1.add(jMenu8);

        jMenu9.setText(" Utilities");

        mnuchangepassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile1.jpg"))); // NOI18N
        mnuchangepassword.setText(" Change Password");
        mnuchangepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuchangepasswordActionPerformed(evt);
            }
        });
        jMenu9.add(mnuchangepassword);
        jMenu9.add(jSeparator12);

        mnuapplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_go.png"))); // NOI18N
        mnuapplication.setText("Lock Application");
        mnuapplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuapplicationActionPerformed(evt);
            }
        });
        jMenu9.add(mnuapplication);
        jMenu9.add(jSeparator14);

        mnuuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_go.png"))); // NOI18N
        mnuuser.setText("Manage Users");
        mnuuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuuserActionPerformed(evt);
            }
        });
        jMenu9.add(mnuuser);
        jMenu9.add(jSeparator13);

        mnubackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_go.png"))); // NOI18N
        mnubackup.setText("Database Backup and Restore");
        mnubackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubackupActionPerformed(evt);
            }
        });
        jMenu9.add(mnubackup);
        jMenu9.add(jSeparator16);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_16x16.png"))); // NOI18N
        jMenu14.setText("Application");

        mnucal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        mnucal.setText("Calculator");
        mnucal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucalActionPerformed(evt);
            }
        });
        jMenu14.add(mnucal);
        jMenu14.add(jSeparator17);

        mnunotepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notepad1.png"))); // NOI18N
        mnunotepad.setText("Notepad");
        mnunotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnunotepadActionPerformed(evt);
            }
        });
        jMenu14.add(mnunotepad);
        jMenu14.add(jSeparator18);

        mnupaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        mnupaint.setText("MS paint");
        mnupaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnupaintActionPerformed(evt);
            }
        });
        jMenu14.add(mnupaint);
        jMenu14.add(jSeparator19);

        jMenu15.setText("MS Office");

        mnuword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ecommerce_Icons_Rose_Color-50-32.png"))); // NOI18N
        mnuword.setText("MS Word");
        mnuword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuwordActionPerformed(evt);
            }
        });
        jMenu15.add(mnuword);
        jMenu15.add(jSeparator23);

        mnuexcle.setText("MS Excle");
        mnuexcle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexcleActionPerformed(evt);
            }
        });
        jMenu15.add(mnuexcle);
        jMenu15.add(jSeparator24);

        mnupowerpoint.setText("MS Powerpoint");
        mnupowerpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnupowerpointActionPerformed(evt);
            }
        });
        jMenu15.add(mnupowerpoint);
        jMenu15.add(jSeparator25);

        mnuaccess.setText("MS Access");
        mnuaccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuaccessActionPerformed(evt);
            }
        });
        jMenu15.add(mnuaccess);

        jMenu14.add(jMenu15);
        jMenu14.add(jSeparator26);

        jMenu16.setText("Bowser");

        mnuchrome.setText("Google Chrome");
        mnuchrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuchromeActionPerformed(evt);
            }
        });
        jMenu16.add(mnuchrome);
        jMenu16.add(jSeparator28);

        mnufirebox.setText("Mozila Firebox ");
        mnufirebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnufireboxActionPerformed(evt);
            }
        });
        jMenu16.add(mnufirebox);
        jMenu16.add(jSeparator27);

        mnuexplore.setText("Internet Explore");
        mnuexplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexploreActionPerformed(evt);
            }
        });
        jMenu16.add(mnuexplore);

        jMenu14.add(jMenu16);

        jMenu9.add(jMenu14);
        jMenu9.add(jSeparator15);

        jMenuBar1.add(jMenu9);

        jMenu10.setText(" Exit");

        mnulogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_32x32.png"))); // NOI18N
        mnulogout.setText("Logout");
        mnulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnulogoutActionPerformed(evt);
            }
        });
        jMenu10.add(mnulogout);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnusupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusupplierActionPerformed
        // supplier
        DepartmentForm f=new DepartmentForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnusupplierActionPerformed

    private void mnulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnulogoutActionPerformed
        // logout
        dispose();
        LoginForm f=new LoginForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnulogoutActionPerformed

    private void mnubackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnubackupActionPerformed

    private void mnufireboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnufireboxActionPerformed
       // Firefox
        Utility.executeApp("firefox.exe");
    }//GEN-LAST:event_mnufireboxActionPerformed

    private void mnuexploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexploreActionPerformed
        // Internet Explorer
        Utility.executeApp("iexplore.exe");
    }//GEN-LAST:event_mnuexploreActionPerformed

    private void mnucalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucalActionPerformed
        // Calculator
        Utility.executeApp("calc.exe");
    }//GEN-LAST:event_mnucalActionPerformed

    private void mnunotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnunotepadActionPerformed
         // notepad
        Utility.executeApp("notepad.exe");
    }//GEN-LAST:event_mnunotepadActionPerformed

    private void mnupaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnupaintActionPerformed
        // ms paint
        Utility.executeApp("mspaint.exe");
    }//GEN-LAST:event_mnupaintActionPerformed

    private void mnuwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuwordActionPerformed
         // word
        Utility.executeApp("winword.exe");
    }//GEN-LAST:event_mnuwordActionPerformed

    private void mnuexcleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexcleActionPerformed
         // excel
        Utility.executeApp("excel.exe");
    }//GEN-LAST:event_mnuexcleActionPerformed

    private void mnupowerpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnupowerpointActionPerformed
         // power point
        Utility.executeApp("powerpnt.exe");
    }//GEN-LAST:event_mnupowerpointActionPerformed

    private void mnuaccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuaccessActionPerformed
         // MS access
        Utility.executeApp("msaccess.exe");
    }//GEN-LAST:event_mnuaccessActionPerformed

    private void mnuchromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuchromeActionPerformed
         // chrome
        Utility.executeApp("chrome.exe");
    }//GEN-LAST:event_mnuchromeActionPerformed

    private void mnuchangepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuchangepasswordActionPerformed
        //change password
       ChangePasswordForm f=new ChangePasswordForm();
       f.setVisible(true);
    }//GEN-LAST:event_mnuchangepasswordActionPerformed

    private void mnuapplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuapplicationActionPerformed
        // screen lock
        ScreenLockDialog f= new ScreenLockDialog(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_mnuapplicationActionPerformed

    private void mnuuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuuserActionPerformed
        // manage user
        ManageuserForm f=new ManageuserForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuuserActionPerformed

    private void mnucompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucompanyActionPerformed
        //  company
        CompanyForm f=new CompanyForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnucompanyActionPerformed

    private void mnuemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuemployeeActionPerformed
        // employee
        EmployeeForm f=new EmployeeForm();
        f.setVisible(true);
        
    }//GEN-LAST:event_mnuemployeeActionPerformed

    private void mnucompanyinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucompanyinfoActionPerformed
        // company info
        CompanyInfoForm f=new CompanyInfoForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnucompanyinfoActionPerformed

    private void mnusuppreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusuppreportActionPerformed
        // supplier reports
        HashMap<String,Object> map=new HashMap<>();
        String cond=DBClass.pvalue;
        if(cond.equals("")){
            cond="SuppNo like '%%'";
        }
        map.put("param",cond);
        map.put("paramtitle",DBClass.pvalue);
        db.showReport("src/reports/SupplierReport.jrxml",map);
        dispose();
    }//GEN-LAST:event_mnusuppreportActionPerformed

    private void mnucustreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucustreportActionPerformed
        // customer report
        HashMap<String,Object> map=new HashMap<>();
        String cond=DBClass.pvalue;
        if(cond.equals("")){
            cond="CustNo like '%%'";
        }
        map.put("param",cond);
        map.put("paramtitle",DBClass.pvalue);
        db.showReport("src/reports/EmployeeReport.jrxml",map);
        dispose();
    }//GEN-LAST:event_mnucustreportActionPerformed

    private void mnuprodreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuprodreportActionPerformed
        // product report
        
    }//GEN-LAST:event_mnuprodreportActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnudeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnudeptActionPerformed
        // department
        DepartmentForm f=new DepartmentForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnudeptActionPerformed

    private void mnubankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubankActionPerformed
        // bank
        BankForm f=new BankForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnubankActionPerformed

    private void mnuapplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuapplicantActionPerformed
        //purchase order form
      ApplicantForm f=new ApplicantForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuapplicantActionPerformed

    private void mnubankreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubankreportActionPerformed
        //bank report
        HashMap<String,Object> map=new HashMap<>();
        String cond=DBClass.pvalue;
        if(cond.equals("")){
            cond="BankNo like '%%'";
        }
        map.put("param",cond);
        map.put("paramtitle",DBClass.pvalue);
        db.showReport("src/reports/BankReport.jrxml",map);
        dispose();
    }//GEN-LAST:event_mnubankreportActionPerformed

    private void mnuapplicanttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuapplicanttestActionPerformed
        // Material Rrceipt
        ApplicantTestDetailsForm f=new ApplicantTestDetailsForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuapplicanttestActionPerformed

    private void mnuselectedapplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuselectedapplicantActionPerformed
        // TODO add your handling code here:
        SelectedApplicantForm f=new SelectedApplicantForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuselectedapplicantActionPerformed

    private void mnutestditalisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutestditalisActionPerformed
        // Test
        TestForm f=new TestForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnutestditalisActionPerformed

    private void EmplistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmplistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmplistActionPerformed

    private void mnuempattendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuempattendenceActionPerformed
        // TODO add your handling code here:
        EmpAttendenceForm f=new EmpAttendenceForm();
        f.setVisible(true);
                
    }//GEN-LAST:event_mnuempattendenceActionPerformed

    private void mnuleaverequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuleaverequestActionPerformed
        // TODO add your handling code here:
        EmployeeLeaveRequestForm f=new EmployeeLeaveRequestForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuleaverequestActionPerformed

    private void mnusalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusalaryActionPerformed
        // TODO add your handling code here:
        EmployeeSalary f=new EmployeeSalary();
        f.setVisible(true);
    }//GEN-LAST:event_mnusalaryActionPerformed

    private void mnusalaryditailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusalaryditailsActionPerformed
        // TODO add your handling code here:
        EmployeeSalaryDetailsForm f=new EmployeeSalaryDetailsForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnusalaryditailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Emplist;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator31;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JPopupMenu.Separator jSeparator33;
    private javax.swing.JPopupMenu.Separator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator36;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JMenuItem mnuaccess;
    private javax.swing.JMenuItem mnuapplicant;
    private javax.swing.JMenuItem mnuapplicanttest;
    private javax.swing.JMenuItem mnuapplication;
    private javax.swing.JMenuItem mnubackup;
    private javax.swing.JMenuItem mnubank;
    private javax.swing.JMenuItem mnubankreport;
    private javax.swing.JMenuItem mnucal;
    private javax.swing.JMenuItem mnuchangepassword;
    private javax.swing.JMenuItem mnuchrome;
    private javax.swing.JMenuItem mnucompany;
    private javax.swing.JMenuItem mnucompanyinfo;
    private javax.swing.JMenuItem mnucustreport;
    private javax.swing.JMenuItem mnudept;
    private javax.swing.JMenuItem mnuempattendence;
    private javax.swing.JMenuItem mnuemployee;
    private javax.swing.JMenuItem mnuexcle;
    private javax.swing.JMenuItem mnuexplore;
    private javax.swing.JMenuItem mnufirebox;
    private javax.swing.JMenuItem mnuleaverequest;
    private javax.swing.JMenuItem mnulogout;
    private javax.swing.JMenu mnumaster;
    private javax.swing.JMenuItem mnunotepad;
    private javax.swing.JMenuItem mnupaint;
    private javax.swing.JMenuItem mnupowerpoint;
    private javax.swing.JMenuItem mnuprodreport;
    private javax.swing.JMenuItem mnusalary;
    private javax.swing.JMenuItem mnusalaryditails;
    private javax.swing.JMenuItem mnuselectedapplicant;
    private javax.swing.JMenuItem mnusupplier;
    private javax.swing.JMenuItem mnusuppreport;
    private javax.swing.JMenuItem mnutestditalis;
    private javax.swing.JMenuItem mnuuser;
    private javax.swing.JMenuItem mnuword;
    // End of variables declaration//GEN-END:variables
}
