/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrms.forms;

import com.hrms.classes.DBClass;
import com.hrms.classes.ImageUtility;
import com.hrms.classes.Messages;
import com.hrms.classes.Rules;
import com.hrms.classes.StatusClass;
import com.hrms.classes.Utility;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.xml.ws.BindingProvider;

/**
 *
 * @author ADMIN
 */
public class NewBillForm extends javax.swing.JFrame {
        DBClass db=new DBClass();
        String oldname;
  
    /**
     * Creates new form LoginForm
     */
    public NewBillForm() {
        initComponents();
        Utility.setBackground(this, Color.WHITE);
        Utility.setBorder(this);
        ImageUtility.resizeLabelImage(lblimage);
        String id=db.getID("BillNo");
        txtbillno.setText(id);
        txtbilldate.setDate(LocalDate.now());
        KeyboardFocusManager km=KeyboardFocusManager.getCurrentKeyboardFocusManager();
        km.addKeyEventDispatcher(event->{
            if(event.getID()==KeyEvent.KEY_RELEASED){
                if(event.getKeyCode()==KeyEvent.VK_F5){
                    int i=table1.getSelectedRow();
                    if(i!=-1){ //if row is selected
                        DefaultTableModel dt= (DefaultTableModel) table1.getModel();
                        dt.removeRow(i);
                        lbltotal.setText("Total Items #"+dt.getRowCount());                        
                    }
                    return true; //Key is handled by code
                }
            }
            return false; //JVM will handle key
        });
        txtdiscp.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               getTotal();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                getTotal();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        txtgstp.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               getTotal();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                getTotal();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        txtname.requestFocus();
    }
    String formatBillNo(String id){
        String s="B00000";
        s=s.substring(0,id.length()-1);
        s=s+id;
        return s;
    }
    public void setBillInfo(String billno){
        try{
            ResultSet rs=db.getData("select * from Bill where BillNo=?", billno);
            rs.next();
            txtbillno.setText(rs.getString(1));
            txtbilldate.setDate(LocalDate.parse(rs.getString(2)));
            cmbtype.setSelectedItem(rs.getString(3));
            txtcustno.setText(rs.getString(4));
            txtname.setText(rs.getString(5));
            txttotal.setText(rs.getString(6));
            txtdiscp.setText(rs.getString(7));
            txtdiscamt.setText(rs.getString(8));
            txtgstp.setText(rs.getString(9));
            txtgstamt.setText(rs.getString(10));
            txtnetamt.setText(rs.getString(11));
            db.fillTable(table1, "select ProdNo,ProductName,Qty,price,unit,total,discp,discamt,Net from BillItems where BillNo=?",billno);
            btnsave.setText("Update");
            lbltotal.setText("Total Items #"+table1.getRowCount());
            txtname.requestFocus();
        }catch(Exception ex){
            Messages.showError("Error: "+ex.getMessage(), "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtprepared1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtbillno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbilldate = new com.github.lgooddatepicker.components.DatePicker();
        txtname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcustno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiscp = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btncustno = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtdiscamt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtgstamt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtgstp = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtnetamt = new javax.swing.JTextField();
        cmbtype = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtprodno = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtunit = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnprod = new javax.swing.JButton();
        txtqty = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtdiscp1 = new javax.swing.JTextField();
        lbltotal = new javax.swing.JLabel();
        lbldelete = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("DISC%");

        txtprepared1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprepared1.setToolTipText("Please enter valid username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setText("Sales Bill");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        btnclose.setBackground(new java.awt.Color(255, 255, 255));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setText("X");
        btnclose.setToolTipText("Exit from Application");
        btnclose.setContentAreaFilled(false);
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.setOpaque(true);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnreset.setBackground(new java.awt.Color(51, 255, 204));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.setContentAreaFilled(false);
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.setOpaque(true);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(51, 255, 204));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.setContentAreaFilled(false);
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.setOpaque(true);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product No", "Product Name ", "Qty ", "Price", "Unit", "Total", "Disc%", "DiscAmt", "NetAmt"
            }
        ));
        jScrollPane3.setViewportView(table1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales Bill Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel14.setText("Bill No");
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtbillno.setEditable(false);
        txtbillno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbillno.setToolTipText("Please enter valid username");

        jLabel15.setText("Bill Date");
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtname.setToolTipText("Please enter valid username");

        jLabel7.setText("Customer Name");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setText("Customer No");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtcustno.setEditable(false);
        txtcustno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcustno.setToolTipText("Please enter valid username");

        jLabel9.setText("Total Amt");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdiscp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdiscp.setToolTipText("Please enter valid username");

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotal.setToolTipText("Please enter valid username");

        jLabel16.setText("Disc%");
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btncustno.setText("...");
        btncustno.setBackground(new java.awt.Color(51, 255, 204));
        btncustno.setContentAreaFilled(false);
        btncustno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncustno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncustno.setOpaque(true);
        btncustno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustnoActionPerformed(evt);
            }
        });

        jLabel22.setText("Transtype");
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel24.setText("DiscAmt");
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdiscamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdiscamt.setToolTipText("Please enter valid username");

        jLabel25.setText("GST Amt");
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtgstamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgstamt.setToolTipText("Please enter valid username");

        jLabel26.setText("GST%");
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtgstp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgstp.setToolTipText("Please enter valid username");

        jLabel27.setText("Net Amount");
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtnetamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnetamt.setToolTipText("Please enter valid username");

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtbillno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcustno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncustno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbilldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal))
                        .addGap(168, 168, 168))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiscp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgstp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdiscamt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtgstamt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel22)
                                .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtbilldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtdiscp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiscamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtgstamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(txtgstp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtbillno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(txtnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtcustno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncustno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales Items Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel18.setText("Product No");
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtprodno.setEditable(false);
        txtprodno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprodno.setToolTipText("Please enter valid username");

        jLabel19.setText("Product  Name");
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtpname.setEditable(false);
        txtpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpname.setToolTipText("Please enter valid username");

        jLabel20.setText("Qty");
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel21.setText("Unit");
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtunit.setEditable(false);
        txtunit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtunit.setToolTipText("Please enter valid username");

        btnadd.setText("Add");
        btnadd.setBackground(new java.awt.Color(51, 255, 204));
        btnadd.setContentAreaFilled(false);
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setOpaque(true);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnprod.setText("...");
        btnprod.setBackground(new java.awt.Color(51, 255, 204));
        btnprod.setContentAreaFilled(false);
        btnprod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprod.setOpaque(true);
        btnprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodActionPerformed(evt);
            }
        });

        txtqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel28.setText("Price");
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprice.setToolTipText("Please enter valid username");

        jLabel29.setText("Disc%");
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdiscp1.setEditable(false);
        txtdiscp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdiscp1.setToolTipText("Please enter valid username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtprodno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtdiscp1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiscp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprodno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbltotal.setText("Total Items #");
        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbldelete.setText("F5-Delete Item Entry");
        lbldelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbldelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltotal)
                    .addComponent(lbldelete))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // close
       dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // Reset
        txtbillno.setText(db.getID("BillNo"));
        txtbilldate.setText("");
        txtcustno.setText(null); //Clear textbox
        txtname.setText("");        
        txttotal.setText("");
        txtdiscp.setText("");
        txtprodno.setText("");
        txtpname.setText("");
        txtqty.setText("");
        txtprice.setText("");
        lbltotal.setText("Total Items #");
        DefaultTableModel dt=(DefaultTableModel) table1.getModel();
        dt.setRowCount(0); //Clear all rows in Table
        btnsave.setText("Save");
        txtname.requestFocus();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       // Save
        String billno=txtbillno.getText();
        if(txtbilldate.getText().equals("")){
            Messages.showWarning("Bill Date cannot be left empty", "Input Error");
            txtbilldate.requestFocus();
            return;
        }
        String type=cmbtype.getSelectedItem()+"";
        String billdate=txtbilldate.getDate().format(DateTimeFormatter.ISO_DATE);
        String custno=txtcustno.getText();
        String custname=txtname.getText();
        String total=txttotal.getText();
        String discp=txtdiscp.getText();
        String discamt=txtdiscamt.getText();
        String gstp=txtgstp.getText();
        String gstamt=txtgstamt.getText();
        String netamt=txtnetamt.getText();
        
        //Apply Validation
        if(custname.equals("")){
            Messages.showWarning("Customer Name cannot be left empty", "Input Error");
            txtname.requestFocus();
            return;
        }
        if(total.equals("")){
            Messages.showWarning("Total Amt cannot be left empty", "Input Error");
            txttotal.requestFocus();
            return;
        }
        if(!Rules.isDouble(total)){
            Messages.showWarning("Total Amt should be in numeric format", "Input Error");
            txttotal.requestFocus();
            return;
        }
        if(discp.equals("")){
            Messages.showWarning("Discount Percent cannot be left empty", "Input Error");
            txtdiscp.requestFocus();
            return;
        }
        if(!Rules.isDouble(discp)){
            Messages.showWarning("Total Amt should be in numeric format", "Input Error");
            txttotal.requestFocus();
            return;
        }
        if(gstp.equals("")){
            Messages.showWarning("GST Tax Percent cannot be left empty", "Input Error");
            txtgstp.requestFocus();
            return;
        }
        if(!Rules.isDouble(gstamt)){
            Messages.showWarning("GST Amt should be in numeric format", "Input Error");
            txtgstamt.requestFocus();
            return;
        }
        if(netamt.equals("")){
            Messages.showWarning("Bet Amount cannot be left empty", "Input Error");
            txtnetamt.requestFocus();
            return;
        }
        if(!Rules.isDouble(netamt)){
            Messages.showWarning("Net Amt should be in numeric format", "Input Error");
            txtnetamt.requestFocus();
            return;
        }
        
        String btntext=btnsave.getText();
        if(btntext.equals("Save")){
            db.execute("Insert into Bill values(?,?,?,?,?,?,?,?,?,?,?)",billno,billdate,type,custno,custname,total,discp,discamt,gstp,gstamt,netamt);
            db.updateID("BillNo");
        
            for(int i=0;i<table1.getRowCount();i++){
                String prodno=table1.getValueAt(i, 0)+"";
                String pname=table1.getValueAt(i, 1)+"";
                String qty=table1.getValueAt(i, 2)+"";
                String price=table1.getValueAt(i, 3)+"";
                String unit=table1.getValueAt(i, 4)+"";
                String totalamt=table1.getValueAt(i, 5)+"";
                String discp1=table1.getValueAt(i, 6)+"";
                String discamt1=table1.getValueAt(i, 7)+"";
                String netamt1=table1.getValueAt(i, 8)+"";
                db.execute("Insert into BillItems values(?,?,?,?,?,?,?,?,?,?)",billno,prodno,pname,qty,price,unit,totalamt,discp1,discamt1,netamt1);
                //Update stock of each item
                db.execute("Update Product set Qty=Qty-? where ProdNo=?",qty,prodno);
            }
            if(type.equals("CREDIT"))
            db.execute("Update Customer Set ACBalance=ACBalance+? where CustNo=?", netamt,custno);
            Messages.showInfo("Bill is created Successfully...", "Success");                
        }else{
            db.execute("Update Bill set BillDate=?,TransType=?,CustNo=?,Custname=?,TotalAmt=?,Discp=?,Discamt=?,gst=?,GStamt=?,NetAmt=? where BillNo=?",billdate,type,custno,custname,total,discp,discamt,gstp,gstamt,netamt,billno);
            try{
            //Restore Stock/Reverse enrty of stock
            ResultSet rs=db.getData("select * from BillItems where BillNo=?", billno);
            while(rs.next()){
                db.execute("update product set qty=qty-? where ProdNo=?", rs.getString(4),rs.getString(2));
            }
            }catch(Exception ex){
                System.out.println("Error:  "+ex.getMessage());
            }
            //Delete all child entries from BillItems table
            db.execute("delete from BillItems where BillNo=?", billno);
            
            //Insert child entries from Table
            for(int i=0;i<table1.getRowCount();i++){
                String prodno=table1.getValueAt(i, 0)+"";
                String pname=table1.getValueAt(i, 1)+"";
                String qty=table1.getValueAt(i, 2)+"";
                String price=table1.getValueAt(i, 3)+"";
                String unit=table1.getValueAt(i, 4)+"";
                String totalamt=table1.getValueAt(i, 5)+"";
                String discp1=table1.getValueAt(i, 6)+"";
                String discamt1=table1.getValueAt(i, 7)+"";
                String netamt1=table1.getValueAt(i, 8)+"";
                db.execute("Insert into BillItems values(?,?,?,?,?,?,?,?,?,?)",billno,prodno,pname,qty,price,unit,totalamt,discp1,discamt1,netamt1);
                //Update stock of each item
                db.execute("Update Product set Qty=Qty+? where ProdNo=?",qty,prodno);
            }
            Messages.showInfo("Bill is updated Successfully...", "Success");                
        }        
        db.fillTable(BillListForm.table1, "select * from Bill");
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodActionPerformed
        // Open Product Form
        ProductForm f=new ProductForm();
        f.table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int i=f.table1.getSelectedRow();
                if(i!=-1){ //if row is selected
                    txtprodno.setText(f.table1.getValueAt(i, 0)+"");
                    txtpname.setText(f.table1.getValueAt(i, 1)+"");
                    txtprice.setText(f.table1.getValueAt(i, 4)+"");
                    txtunit.setText(f.table1.getValueAt(i, 5)+"");
                    f.dispose();
                    txtqty.requestFocus();
                }
            }
            
        });
        f.setVisible(true);
    }//GEN-LAST:event_btnprodActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        //Add Item
        String pid=txtprodno.getText();
        String pname=txtpname.getText();
        String qty=txtqty.getText();
        String price=txtprice.getText();
        String unit=txtunit.getText();
        double total=Integer.parseInt(qty)*Double.parseDouble(price);
        String discp=txtdiscp1.getText();
        if(discp.equals("")){
            discp="0";
        }
        double discamt=total*(Double.parseDouble(discp)/100);
        double net=total-discamt;              
        DefaultTableModel dt= (DefaultTableModel) table1.getModel();
        Object obj[]={pid,pname,qty,price,unit,total,discp,discamt,net};
        dt.addRow(obj);
        lbltotal.setText("Total Items #"+dt.getRowCount());
        getTotal();
        btnprod.requestFocus();
    }//GEN-LAST:event_btnaddActionPerformed
  void getTotal(){
       double total=0;
        for(int i=0;i<table1.getRowCount();i++){
            total+= Double.parseDouble(table1.getValueAt(i, 8)+"");
        }
        DecimalFormat df=new DecimalFormat("0.00");
        //format method==> formats given double no and returns string
        txttotal.setText(df.format(total));
        String discp=txtdiscp.getText();//5 1 10 6
        if(discp.equals("")){
            discp="0";
        }
        String gsttax=txtgstp.getText();
        if(gsttax.equals("")){
            gsttax="0";
        }
        double discamt=total*(Double.parseDouble(discp)/100);
        total=total-discamt;
        double gstamt=total*(Double.parseDouble(gsttax)/100);
        total=total+gstamt;
        
        //txtdiscp.setText(discp);
        txtdiscamt.setText(df.format(discamt));
        //txtgstp.setText(gsttax);
        txtgstamt.setText(df.format(gstamt));
        txtnetamt.setText(df.format(total));
  }
    private void btncustnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustnoActionPerformed
        // Open Supplier Form
        CustomerForm f=new CustomerForm();
        f.table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int i=f.table1.getSelectedRow();
                if(i!=-1){ //if row is selected
                    txtcustno.setText(f.table1.getValueAt(i, 0)+"");
                    txtname.setText(f.table1.getValueAt(i, 1)+"");
                    f.dispose();
                }
            }
            
        });
        f.setVisible(true);
    }//GEN-LAST:event_btncustnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
              
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btncustno;
    private javax.swing.JButton btnprod;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbldelete;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable table1;
    private com.github.lgooddatepicker.components.DatePicker txtbilldate;
    private javax.swing.JTextField txtbillno;
    private javax.swing.JTextField txtcustno;
    private javax.swing.JTextField txtdiscamt;
    private javax.swing.JTextField txtdiscp;
    private javax.swing.JTextField txtdiscp1;
    private javax.swing.JTextField txtgstamt;
    private javax.swing.JTextField txtgstp;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnetamt;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtprepared1;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprodno;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtunit;
    // End of variables declaration//GEN-END:variables

    
    

    

   

    
}
